### ISSUE TITLE
How to create US probe with 3D visualization. 

### ISSUE THREAD

**Issue by kimsekeun** [jhacsonmeza/StructuredLight_3DfreehandUS#2]
Hi, 

how can I create real time us probe navigator as navig.gif?

Thanks

**Comment by jhacsonmeza** [comment]
Hi,

For the 3D visualization we used the [OpenCV 3D Visualizer](https://docs.opencv.org/4.x/d1/d19/group__viz.html) module (which is under the `cv::viz` namespace). To use it you need to compile OpenCV with [VTK](https://vtk.org/) support. Although you don't necessarily need to use OpenCV for 3D visualization, you can use any other library or API.

You also need a 3D model of an ultrasound probe for real time visualization. I'm sharing with you the mesh we used [USprobe.txt](https://github.com/user-attachments/files/16920972/USprobe.txt) (I shared it as a .txt file because I couldn't upload it as .ply. Please change the extension to .ply once you download it). We modified the origin of this model to be aligned with the ultrasound image coordinate system (which is exactly the one you establish during the probe calibration). In this way, you can use exactly the same transformations you use to map the ultrasound image to the 3D space, to also transform the mesh.

This a general idea of the code:
```C++
cv::viz::Mesh X = cv::viz::Mesh::load("path/to/USprobe.ply");
cv::viz::WMesh probe(X);

cv::Mat USim = cv::imread("path/to/US image",0);
int w = USim.cols, h = USim.rows;
cv::viz::WImage3D slice(im, {w*sx,h*sy}, {0.5*w*sx,0.5*h*sy,0}, {0,0,1}, {0,1,0});


cv::viz::Viz3d myWindow("3D vis");
myWindow.showWidget("Probe", probe);
myWindow.showWidget("Slice", slice);


// Visualization loop
while (true) {
    // Get image to world transformation
    cv::Affine3f T_I_W = ...;
    
    // Update ultrasound probe pose
    myWindow.setWidgetPose("Probe", T_I_W);
    
    // Read current US image
    cv::Mat USim = cv::imread(...);
    // Set current ultrasound image to the slice object
    slice.setImage(USim);
    // Update image pose
    myWindow.setWidgetPose("Slice", T_I_W);
    myWindow.spinOnce(1, false);
}
```
Hope this can help.
